# Create CouchDB Instance 1 on MRC
- name: Create CouchDB instances
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor_1c4g }}'
    availability_zone: '{{ availability_zone }}'
    nics: 
      - net-name: qh2-uom
    security_groups: '{{ sg_initial }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ couchdb_instance_1 }}'
  register: os_instance

# Settig CouchDB instance 1 fact
- name: Setting couchdb_instance_1_ip fact
  set_fact:
    couchdb_instance_1_ip: "{{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'  
  when: item.openstack is defined

# Create CouchDB Instance 2 on MRC
- name: Create CouchDB instances
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor_1c4g }}'
    availability_zone: '{{ availability_zone }}'
    nics: 
      - net-name: qh2-uom
    security_groups: '{{ sg_initial }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ couchdb_instance_2 }}'
  register: os_instance

# Settig CouchDB Instance 2 IP fact
- name: Setting couchdb_instance_1_ip fact
  set_fact:
    couchdb_instance_2_ip: "{{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'  
  when: item.openstack is defined

# Create Twitter Harvester instance
- name: Create Twitter Harvester Instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor_2c9g }}'
    availability_zone: '{{ availability_zone }}'
    nics: 
      - net-name: qh2-uom
    security_groups: '{{ sg_initial }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ harvester_instance }}'
  register: os_instance

# Settig Twitter Harvester IP fact
- name: Setting couchdb_instance_1_ip fact
  set_fact:
    twitter_harvester_ip: "{{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'  
  when: item.openstack is defined

# Create Web Front End Instance
- name: Create Web Front-End Instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor_2c9g }}'
    availability_zone: '{{ availability_zone }}'
    nics: 
      - net-name: qh2-uom
    security_groups: '{{ sg_initial }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ web_front_end_instance }}'
  register: os_instance 

# Settig Twitter Harvester IP fact
- name: Setting couchdb_instance_1_ip fact
  set_fact:
    web_front_end_ip: "{{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'  
  when: item.openstack is defined

- debug:
    msg: " CouchDB instance 1 has IP {{ couchdb_instance_1_ip }}, {{ couchdb_instance_2_ip }}, {{ twitter_harvester_ip }} {{ web_front_end_ip }}"