# Create a security group
- name: Creating SSH access from all Security Group
  os_security_group:
    name: 'SSH access from all'
    description: 'Allow SSH access from anywhere'
    state: present

# Create security group rules
- name: Creating SSH access from all security group rules
  os_security_group_rule:
    security_group: 'SSH access from all'
    protocol: 'tcp'
    port_range_min: '22'
    port_range_max: '22'
    remote_ip_prefix: '0.0.0.0/0'
    state: present

- name: Creating sg_initial initial Security Group List
  set_fact:
    sg_initial: ["SSH access from all"]

- debug:
    msg: "{ sg_initial }} SEcurity Group created."