# Creating SSH access from all security group
- name: Creating 'SSH access from all' Security Group
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ ssh-ingress-security-group }}'

# Applying security group rules to SSH access from all
- name: Creating SSH ingress port rule (22) for 'SSH access from all'
  os_security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    direction: '{{ item.direction }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ item.ip_prefix }}'
    state: present'
  loop: '{{ ssh-ingress-security-group }}'

- name: Create a ssh_access list fact (for initial isntance application)
  set_fact:
    ssh_access: ["SSH access from all"]

- debug:
    msg: "Initial SSH Access Security Group created: {{ ssh_access }}"