# Create CouchDB Instance 0 on MRC
- name: Create CouchDB instances
  os_server:
    name: '{{ item.name }}'
    image: '{{ item.image }}'
    key_name: '{{ item.key_name }}'
    flavor: '{{ item.flavour }}'
    availability_zone: '{{ item.availability_zone }}'
    nics: 
      - net-name: '{{ item.network }}'
    security_groups: '{{ ssh_access }}'
    volumes: '{{ item.volume }}' 
    auto_floating_ip: yes
    wait: yes
    timeout: 500
    state: present
  loop: '{{ couchdb_instance_0 }}'
  register: os_instance

# Settig CouchDB instance 0 fact
- name: Setting couchdb_instance_0_ip fact
  set_fact:
    couchdb_instance_0_ip: "{{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'  
  when: item.openstack is defined

# Create CouchDB Instance 1 on MRC
- name: Create CouchDB instances
  os_server:
    name: '{{ item.name }}'
    image: '{{ item.image }}'
    key_name: '{{ item.key_name }}'
    flavor: '{{ item.flavour }}'
    availability_zone: '{{ item.availability_zone }}'
    nics: 
      - net-name: '{{ item.network }}'
    security_groups: '{{ ssh_access }}'
    volumes: '{{ item.volume }}' 
    auto_floating_ip: yes
    wait: yes
    timeout: 500
    state: present
  loop: '{{ couchdb_instance_1 }}'
  register: os_instance

# Settig CouchDB instance 1 fact
- name: Setting couchdb_instance_1_ip fact
  set_fact:
    couchdb_instance_1_ip: "{{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'  
  when: item.openstack is defined

# Create CouchDB Instance 2 on MRC
- name: Create CouchDB instances
  os_server:
    name: '{{ item.name }}'
    image: '{{ item.image }}'
    key_name: '{{ item.key_name }}'
    flavor: '{{ item.flavour }}'
    availability_zone: '{{ item.availability_zone }}'
    nics: 
      - net-name: '{{ item.network }}'
    security_groups: '{{ ssh_access }}'
    volumes: '{{ item.volume }}' 
    auto_floating_ip: yes
    wait: yes
    timeout: 500
    state: present
  loop: '{{ couchdb_instance_2 }}'
  register: os_instance

# Settig CouchDB Instance 2 IP fact
- name: Setting couchdb_instance_1_ip fact
  set_fact:
    couchdb_instance_2_ip: "{{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'  
  when: item.openstack is defined

# Create Web Front End Instance
- name: Create Web Front-End Instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ item.image }}'
    key_name: '{{ item.key_name }}'
    flavor: '{{ item.flavour }}'
    availability_zone: '{{ item.availability_zone }}'
    nics: 
      - net-name: '{{ item.network }}'
    security_groups: '{{ ssh_access }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 500
    state: present
  loop: '{{ web_front_end_instance }}'
  register: os_instance 

# Settig Web front end ip IP fact
- name: Setting web front end ip fact
  set_fact:
    web_front_end_ip: "{{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'  
  when: item.openstack is defined

