# CouchDB Instances 0, 1, and 2
couchdb_instance_0:
  - name: couchdb-a2-0
    image: 916cad7a-c545-48b2-b36c-d509ee63b3ce
    flavour: uom.mse.1c4g
    key_name: benKP
    availability_zone: melbourne-qh2-uom
    network: qh2-uom
    volume: couchdb0_vol_1

couchdb_instance_1:
  - name: couchdb-a2-1
    image: 916cad7a-c545-48b2-b36c-d509ee63b3ce
    flavour: uom.mse.1c4g
    key_name: benKP
    availability_zone: melbourne-qh2-uom
    network: qh2-uom
    volume: couchdb1_vol_1

couchdb_instance_2:
  - name: couchdb-a2-2
    image: 916cad7a-c545-48b2-b36c-d509ee63b3ce
    flavour: uom.mse.1c4g
    key_name: benKP
    availability_zone: melbourne-qh2-uom
    network: qh2-uom
    volume: couchdb2_vol_1

# Web front end Instance
web_front_end_instance:
  - name: web-fe-a2-1
    image: 916cad7a-c545-48b2-b36c-d509ee63b3ce
    flavour: uom.mse.2c9g
    key_name: benKP
    availability_zone: melbourne-qh2-uom
    network: qh2-uom