- name: "Enable Clustering for Node 0"
  remote_user: ubuntu
  uri:
      url: http://localhost:5984/_cluster_setup
      force_basic_auth: yes
      user: "admin"
      password: "password"
      method: POST 
      body: '{"action": "enable_cluster", "bind_address": "0.0.0.0", "username": "admin", "password":"password", "node_count":"3"}'
      body_format: json
      status_code: 400
      return_content: yes
  delegate_to: '{{ couchdb_instance_0_ip }}'

- name: "Enable Clustering for Node 1"
  remote_user: ubuntu
  uri:
      url: http://localhost:5984/_cluster_setup
      force_basic_auth: yes
      user: "admin"
      password: "password"
      method: POST 
      body: '{"action": "enable_cluster", "bind_address": "0.0.0.0", "username": "admin", "password":"password", "node_count":"3"}'
      body_format: json
      status_code: 400
      return_content: yes
  delegate_to: '{{ couchdb_instance_1_ip }}'

- name: "Enable Clustering for Node 2"
  remote_user: ubuntu
  uri:
      url: http://localhost:5984/_cluster_setup
      force_basic_auth: yes
      user: "admin"
      password: "password"
      method: POST 
      body: '{"action": "enable_cluster", "bind_address": "0.0.0.0", "username": "admin", "password":"password", "node_count":"3"}'
      body_format: json
      status_code: 400
      return_content: yes
  delegate_to: '{{ couchdb_instance_2_ip }}'

- name: "Coordinate Cluster Setup on Node 0: connecting to Node 1 - p1"
  remote_user: ubuntu
  uri:
      url: http://localhost:5984/_cluster_setup
      force_basic_auth: yes
      user: "admin"
      password: "password"
      method: POST 
      body: '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"password", "port": 5984, "node_count": "3", "remote_node": "{{ couchdb_instance_1_ip }}", "remote_current_user": "admin", "remote_current_password": "password" }'
      body_format: json
      # status_code: 400
      status_code: 201
      return_content: yes
  delegate_to: '{{ couchdb_instance_0_ip }}'

- name: "Coordinate Cluster Setup on Node 0: connecting to Node 1 - p2"
  remote_user: ubuntu
  uri:
      url: http://localhost:5984/_cluster_setup
      force_basic_auth: yes
      user: "admin"
      password: "password"
      method: POST 
      body: '{"action": "add_node", "host":"{{ couchdb_instance_1_ip }}", "port": 5984, "username": "admin", "password":"password"}'
      body_format: json
      # status_code: 400
      status_code: 201
      return_content: yes
  delegate_to: '{{ couchdb_instance_0_ip }}'

- name: "Coordinate Cluster Setup on Node 0: connecting to Node 2 - p1"
  remote_user: ubuntu
  uri:
      url: http://localhost:5984/_cluster_setup
      force_basic_auth: yes
      user: "admin"
      password: "password"
      method: POST 
      body: '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"password", "port": 5984, "node_count": "3", "remote_node": "{{ couchdb_instance_2_ip }}", "remote_current_user": "admin", "remote_current_password": "password" }'
      body_format: json
      # status_code: 400
      status_code: 201
      return_content: yes
  delegate_to: '{{ couchdb_instance_0_ip }}'

- name: "Coordinate Cluster Setup on Node 0: connecting to Node 2 - p2"
  remote_user: ubuntu
  uri:
      url: http://localhost:5984/_cluster_setup
      force_basic_auth: yes
      user: "admin"
      password: "password"
      method: POST 
      body: '{"action": "add_node", "host":"{{ couchdb_instance_2_ip }}", "port": 5984, "username": "admin", "password":"password"}'
      body_format: json
      # status_code: 400
      status_code: 201
      return_content: yes
  delegate_to: '{{ couchdb_instance_0_ip }}'


- name: "Finalise Cluster Configuration on Node 0"
  remote_user: ubuntu
  uri:
      url: http://localhost:5984/_cluster_setup
      force_basic_auth: yes
      user: "admin"
      password: "password"
      method: POST 
      body: '{"action": "finish_cluster"}'
      body_format: json
      # status_code: 400
      status_code: 201
      return_content: yes
  delegate_to: '{{ couchdb_instance_0_ip }}'


- name: "Setup CORS for Cluster - p1"
  remote_user: ubuntu
  uri:
      url: http://localhost:5984/_node/couchdb@{{ couchdb_instance_0_ip }}/_config/httpd/enable_cors
      force_basic_auth: yes
      user: "admin"
      password: "password"
      method: PUT 
      body: '"true"'
      body_format: json
      status_code: 200
      return_content: yes
  delegate_to: '{{ couchdb_instance_0_ip }}'

- name: "Setup CORS for Cluster - p2"
  remote_user: ubuntu
  uri:
      url: http://localhost:5984/_node/couchdb@{{ couchdb_instance_0_ip }}/_config/cors/origins
      force_basic_auth: yes
      user: "admin"
      password: "password"
      method: PUT 
      body: '"*"'
      body_format: json
      status_code: 200
      return_content: yes
  delegate_to: '{{ couchdb_instance_0_ip }}'

# Add DBs

- name: "Create Tweet DBs"
  remote_user: ubuntu
  uri:
      url: http://localhost:5984/tweets
      force_basic_auth: yes
      user: "admin"
      password: "password"
      method: PUT 
      status_code: 201
      return_content: yes
  delegate_to: '{{ couchdb_instance_0_ip }}'

- name: "Create front_end DB"
  remote_user: ubuntu
  uri:
      url: http://localhost:5984/front_end
      force_basic_auth: yes
      user: "admin"
      password: "password"
      method: PUT 
      status_code: 201
      return_content: yes
  delegate_to: '{{ couchdb_instance_0_ip }}'
