- debug:
    msg: " CouchDB instance 1 has IP {{ couchdb_instance_1_ip }}, {{ couchdb_instance_2_ip }}, {{ twitter_harvester_ip }} {{ web_front_end_ip }}"

# Create CouchDB 1 Ingress Security Groups
- name: Create "CDB2 CouchDB Ingress from CDB1" Security Group
  os_security_group:
    name: 'CDB2 CouchDB Ingress from CDB1'
    description: 'Allowing traffic on CouchDB Ports from CDB1'
    state: present

- name: Create "CDB2 HTTP/HTTPS Ingress from Harvester" Security Group
  os_security_group:
    name: 'CDB2 HTTP/HTTPS Ingress from Harvester'
    description: 'Allowing traffic on HTTP and HTTPS Ports from Harvester'
    state: present

# Attach CouchDB Port rules to SG
- name: Attach Security Group rules (CouchDB ports) for "CDB2 CouchDB Ingress from CDB1"
  os_security_group_rule:
    security_group: 'CDB2 CouchDB Ingress from CDB1'
    protocol: 'tcp'
    direction: 'ingress'
    port_range_min: '{{ item }}'
    port_range_max: '{{ item }}'
    remote_ip_prefix: '{{ couchdb_instance_1_ip }}/32'
    state: present
  loop: '{{ couchdb_ports }}'

- name: Attach Security Group rules (HTTP port) for "CDB2 HTTP/HTTPS Ingress from Harvester"
  os_security_group_rule:
    security_group: 'CDB2 HTTP/HTTPS Ingress from Harvester'
    protocol: 'tcp'
    direction: 'ingress'
    port_range_min: '80'
    port_range_max: '80'
    remote_ip_prefix: '{{ twitter_harvester_ip }}/32'
    state: present

- name: Attach Security Group rules (HTTPS port) for "CDB2 HTTP/HTTPS Ingress from Harvester"
  os_security_group_rule:
    security_group: 'CDB2 HTTP/HTTPS Ingress from Harvester'
    protocol: 'tcp'
    direction: 'ingress'
    port_range_min: '443'
    port_range_max: '443'
    remote_ip_prefix: '{{ twitter_harvester_ip }}/32'
    state: present

# Create CouchDB 1 Egress Security Groups
- name: Create "CDB2 CouchDB Egress to CDB1" Security Group
  os_security_group:
    name: 'CDB2 CouchDB Egress to CDB1'
    description: 'Allowing traffic on CouchDB Ports to CDB1'
    state: present

- name: Create "CDB2 HTTP/HTTPS Egress to Webserver" Security Group
  os_security_group:
    name: 'CDB2 HTTP/HTTPS Egress to Webserver'
    description: 'Allowing traffic on HTTP and HTTPS Ports to Webserver'
    state: present

# Attach CouchDB Port rules to SG
- name: Attach Security Group rules (CouchDB ports) for "CDB2 CouchDB Egress to CDB1"
  os_security_group_rule:
    security_group: 'CDB2 CouchDB Egress to CDB1'
    protocol: 'tcp'
    direction: 'egress'
    port_range_min: '{{ item }}'
    port_range_max: '{{ item }}'
    remote_ip_prefix: '{{ couchdb_instance_1_ip }}/32'
    state: present
  loop: '{{ couchdb_ports }}'

- name: Attach Security Group rules (HTTP port) for "CDB2 HTTP/HTTPS Egress to Webserver"
  os_security_group_rule:
    security_group: 'CDB2 HTTP/HTTPS Egress to Webserver'
    protocol: 'tcp'
    direction: 'egress'
    port_range_min: '80'
    port_range_max: '80'
    remote_ip_prefix: '{{ web_front_end_ip }}/32'  

- name: Attach Security Group rules (HTTPS port) for "CDB2 HTTP/HTTPS Egress to Webserver"
  os_security_group_rule:
    security_group: 'CDB2 HTTP/HTTPS Egress to Webserver'
    protocol: 'tcp'
    direction: 'egress'
    port_range_min: '443'
    port_range_max: '443'
    remote_ip_prefix: '{{ web_front_end_ip }}/32'  

# Setting additional rules list
- name: Setting additional CouchDB2 instance rules list
  set_fact:
    couchdb2_sg: ["SSH access from all", 
     "CDB2 CouchDB Ingress from CDB1",
     "CDB2 HTTP/HTTPS Ingress from Harvester",
     "CDB2 CouchDB Egress to CDB1",
     "CDB2 HTTP/HTTPS Egress to Webserver"]

- debug:
    msg: "Security group(s) {{ couchdb2_sg }} have been created."

