# Create CouchDB Instance 1 volume on MRC
- name: Create volume for CouchDB1 instance
  os_volume:
    display_name: '{{ item.name }}'
    size: '{{ item.size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 300
    state: present
  loop: '{{ couchdb1_volumes }}'
  register: os_vol

# Set couchdb1_vols list
- name: Set couchdb1_vols fact 
  set_fact:
    couchdb1_vols: [ item.id ] 
  loop: '{{ os_vol.results }}'

# Create CouchDB Instance 1 volume on MRC
- name: Create volume for CouchDB2 instance
  os_volume:
    display_name: '{{ item.name }}'
    size: '{{ item.size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 300
    state: present
  loop: '{{ couchdb2_volumes }}'
  register: os_vol

# Set couchdb1_vols list
- name: Set couchdb2_vols fact 
  set_fact:
    couchdb2_vols: [ item.id ] 
  loop: '{{ os_vol.results }}'
