# Create Twitter Harvester instance
- name: Create Twitter Harvester Instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor_2c9g }}'
    availability_zone: '{{ availability_zone }}'
    nics: 
      - net-name: qh2-uom
    security_groups: '{{ harvester_sg }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ harvester_instance }}'
  register: os_instance