# Volumes
couchdb0_volumes:
  - name: couchdb0_vol_1
    availability_zone: melbourne-qh2-uom
    size: 15
    
couchdb1_volumes:
  - name: couchdb1_vol_1
    availability_zone: melbourne-qh2-uom
    size: 15

couchdb2_volumes:
  - name: couchdb2_vol_1
    availability_zone: melbourne-qh2-uom
    size: 15