# Creating SSH access from all security group
- name: Creating 'SSH access from all' Security Group
  os_security_group:
    name: 'SSH access from all'
    description: 'Allow SSH access from anywhere'
    state: present

# Applying security group rules to SSH access from all
- name: Creating SSH ingress port rule (22) for 'SSH access from all'
  os_security_group_rule:
    security_group: 'SSH access from all'
    protocol: 'tcp'
    port_range_min: '22'
    port_range_max: '22'
    remote_ip_prefix: '0.0.0.0/0'
    state: present

- name: Create a ssh_access list fact (for initial isntance application)
  set_fact:
    ssh_access: ["SSH access from all"]

- debug:
    msg: "Security group(s) {{ ssh_access }} have been created."